-- V1__create_tasks_table.sql
--
-- Creates the tasks table backing the new Task entity.
-- Column types mirror the existing tickets table (see static/ddl.sql):
-- timestamp(6) without time zone for audit columns, TEXT for description,
-- varchar for the @Enumerated(EnumType.STRING) fields.
--
-- assigned_member_id references app_users(id) rather than a dedicated
-- team_members table, because TeamMember uses single-table inheritance
-- over AppUser (same pattern as tickets.assigned_member_id).
--
-- NOTE: rename this file's version prefix (V1__) if your project already
-- has other Flyway migrations elsewhere that aren't in this checkout.

CREATE TABLE IF NOT EXISTS tasks
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title              VARCHAR(255) NOT NULL,
    description        TEXT,
    status             VARCHAR(50)  NOT NULL DEFAULT 'PENDING',
    priority           VARCHAR(50)  NOT NULL DEFAULT 'MEDIUM',
    progress           INTEGER      NOT NULL DEFAULT 0,
    due_date           TIMESTAMP(6) WITHOUT TIME ZONE,
    created_at         TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at         TIMESTAMP(6) WITHOUT TIME ZONE,
    assigned_member_id BIGINT,
    CONSTRAINT tasks_pkey PRIMARY KEY (id),
    CONSTRAINT tasks_progress_range_chk CHECK (progress >= 0 AND progress <= 100),
    CONSTRAINT fk_tasks_assigned_member FOREIGN KEY (assigned_member_id)
        REFERENCES app_users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL
);

-- Supports the common filters in TaskSpecification/TaskSearchRequestDto.
CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks (status);
CREATE INDEX IF NOT EXISTS idx_tasks_priority ON tasks (priority);
CREATE INDEX IF NOT EXISTS idx_tasks_assigned_member_id ON tasks (assigned_member_id);
CREATE INDEX IF NOT EXISTS idx_tasks_due_date ON tasks (due_date);
