-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.app_user_roles
(
    app_user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    CONSTRAINT app_user_roles_pkey PRIMARY KEY (app_user_id, role_id)
);

CREATE TABLE IF NOT EXISTS public.app_users
(
    deleted boolean,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    manager_id bigint,
    updated_at timestamp(6) without time zone,
    user_type character varying(31) COLLATE pg_catalog."default" NOT NULL,
    username character varying(50) COLLATE pg_catalog."default",
    availability_status character varying(255) COLLATE pg_catalog."default",
    company_name character varying(255) COLLATE pg_catalog."default",
    department character varying(255) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    first_name character varying(255) COLLATE pg_catalog."default",
    job_title character varying(255) COLLATE pg_catalog."default",
    last_name character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    phone character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT app_users_pkey PRIMARY KEY (id),
    CONSTRAINT app_users_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.flyway_schema_history
(
    installed_rank integer NOT NULL,
    version character varying(50) COLLATE pg_catalog."default",
    description character varying(200) COLLATE pg_catalog."default" NOT NULL,
    type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    script character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    checksum integer,
    installed_by character varying(100) COLLATE pg_catalog."default" NOT NULL,
    installed_on timestamp without time zone NOT NULL DEFAULT now(),
    execution_time integer NOT NULL,
    success boolean NOT NULL,
    CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank)
);

CREATE TABLE IF NOT EXISTS public.permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT permissions_pkey PRIMARY KEY (id),
    CONSTRAINT permissions_code_key UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.role_permissions
(
    permission_id bigint NOT NULL,
    role_id bigint NOT NULL,
    CONSTRAINT role_permissions_pkey PRIMARY KEY (permission_id, role_id)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT roles_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.sla_contracts
(
    is_active boolean,
    response_time_hours integer,
    created_at timestamp(6) without time zone,
    customer_id bigint,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    updated_at timestamp(6) without time zone,
    contract_name character varying(255) COLLATE pg_catalog."default",
    service_scope character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT sla_contracts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ticket_attachments
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    message_id bigint,
    size bigint,
    ticket_id bigint,
    uploaded_at timestamp(6) without time zone,
    uploaded_by_id bigint,
    content_type character varying(100) COLLATE pg_catalog."default",
    file_name character varying(255) COLLATE pg_catalog."default",
    storage_key character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT ticket_attachments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ticket_messages
(
    read_by_customer boolean,
    read_by_team boolean,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    sender_id bigint,
    sent_at timestamp(6) without time zone,
    ticket_id bigint,
    message text COLLATE pg_catalog."default",
    CONSTRAINT ticket_messages_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ticket_status_histories
(
    changed_at timestamp(6) without time zone,
    changed_by_id bigint,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    ticket_id bigint,
    new_status character varying(50) COLLATE pg_catalog."default",
    old_status character varying(50) COLLATE pg_catalog."default",
    note text COLLATE pg_catalog."default",
    CONSTRAINT ticket_status_histories_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tickets
(
    assigned_member_id bigint,
    created_at timestamp(6) without time zone,
    customer_id bigint,
    due_date timestamp(6) without time zone,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    sla_contract_id bigint,
    updated_at timestamp(6) without time zone,
    description text COLLATE pg_catalog."default",
    priority character varying(255) COLLATE pg_catalog."default",
    status character varying(255) COLLATE pg_catalog."default",
    title character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT tickets_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_permission_grants
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    permission_id bigint NOT NULL,
    user_id bigint NOT NULL,
    effect character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT user_permission_grants_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_resource_scopes
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id bigint NOT NULL,
    resource_type character varying(255) COLLATE pg_catalog."default",
    scope character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT user_resource_scopes_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.app_user_roles
    ADD CONSTRAINT fkh1muovnr1tqqsqdhmn5ny6k46 FOREIGN KEY (app_user_id)
    REFERENCES public.app_users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.app_user_roles
    ADD CONSTRAINT fkkxwhjke5g0yvja54osexos75t FOREIGN KEY (role_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.app_users
    ADD CONSTRAINT fk4qh7ik0289g8a9awcmnbtig5g FOREIGN KEY (manager_id)
    REFERENCES public.app_users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.role_permissions
    ADD CONSTRAINT fkegdk29eiy7mdtefy5c7eirr6e FOREIGN KEY (permission_id)
    REFERENCES public.permissions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.role_permissions
    ADD CONSTRAINT fkn5fotdgk8d1xvo8nav9uv3muc FOREIGN KEY (role_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sla_contracts
    ADD CONSTRAINT fkd2tp76lx9cpknggknln7if5wp FOREIGN KEY (customer_id)
    REFERENCES public.app_users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ticket_attachments
    ADD CONSTRAINT fk2997a6qg70pcxiifmsa5cksw0 FOREIGN KEY (uploaded_by_id)
    REFERENCES public.app_users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ticket_attachments
    ADD CONSTRAINT fkddsdoqdixn4l34ssq1ndvk4wb FOREIGN KEY (ticket_id)
    REFERENCES public.tickets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ticket_attachments
    ADD CONSTRAINT fkteqtwhnv6kkbkgubkq20ivw4d FOREIGN KEY (message_id)
    REFERENCES public.ticket_messages (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ticket_messages
    ADD CONSTRAINT fk6gsm2h693a0g41spwfp60w5iv FOREIGN KEY (sender_id)
    REFERENCES public.app_users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ticket_messages
    ADD CONSTRAINT fk8c9vw45c3j5m6arnwp4c3iaby FOREIGN KEY (ticket_id)
    REFERENCES public.tickets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ticket_status_histories
    ADD CONSTRAINT fk64oqc66kcjm00jm2c1qao1tv4 FOREIGN KEY (ticket_id)
    REFERENCES public.tickets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ticket_status_histories
    ADD CONSTRAINT fksas3e1yvejhtro6wiy2e2qpxt FOREIGN KEY (changed_by_id)
    REFERENCES public.app_users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tickets
    ADD CONSTRAINT fkaqjtkqbcd7cfxkioitcxpief8 FOREIGN KEY (sla_contract_id)
    REFERENCES public.sla_contracts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tickets
    ADD CONSTRAINT fke0vc43f58bnuu1h0cdtsos9xk FOREIGN KEY (assigned_member_id)
    REFERENCES public.app_users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tickets
    ADD CONSTRAINT fkq76cjn14xncj8xujpux5juh7 FOREIGN KEY (customer_id)
    REFERENCES public.app_users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_permission_grants
    ADD CONSTRAINT fk9fug45pw94u34wcgdaxpitf1l FOREIGN KEY (permission_id)
    REFERENCES public.permissions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_permission_grants
    ADD CONSTRAINT fklf48t4djtgdhhv1s7swnty29g FOREIGN KEY (user_id)
    REFERENCES public.app_users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_resource_scopes
    ADD CONSTRAINT fkh9ejxkjsexwd2lwt319wqkq8b FOREIGN KEY (user_id)
    REFERENCES public.app_users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;