#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# Squid Proxy Installer + Basic Authentication Setup for AlmaLinux 10
#
# What this script does:
#  1) Installs Squid + required tools (htpasswd via httpd-tools)
#  2) Creates an authentication password file for a single user:
#       username: cent
#       password: sgsec@1390
#  3) Configures Squid to require authentication for proxy access
#  4) Opens firewall port 3128 (if firewalld is running)
#  5) Enables + starts Squid
#
# Notes:
#  - Run as root (or with sudo).
#  - This script will BACK UP your existing /etc/squid/squid.conf before changing it.
#  - Default proxy port used: 3128
# -----------------------------------------------------------------------------

set -euo pipefail

# -----------------------------
# Variables (edit if you want)
# -----------------------------
SQUID_PORT="3128"
SQUID_CONF="/etc/squid/squid.conf"
SQUID_PASSWD_FILE="/etc/squid/passwd"

AUTH_USER="cent"
AUTH_PASS='sgsec@1390'

# -----------------------------
# Helper functions
# -----------------------------
log()  { echo -e "[+] $*"; }
warn() { echo -e "[!] $*" >&2; }
die()  { echo -e "[x] $*" >&2; exit 1; }

need_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    die "This script must be run as root. Try: sudo $0"
  fi
}

cmd_exists() {
  command -v "$1" >/dev/null 2>&1
}

# -----------------------------
# Main
# -----------------------------
need_root

log "Detected OS: AlmaLinux (assumed). Proceeding with DNF-based install..."

# 1) Install Squid + tools needed for basic auth (htpasswd)
#    - squid: the proxy server
#    - httpd-tools: provides 'htpasswd' utility for managing password files
#    - policycoreutils-python-utils: useful for SELinux tooling (optional but handy)
log "Installing packages: squid, httpd-tools, policycoreutils-python-utils ..."
dnf -y install squid httpd-tools policycoreutils-python-utils

# 2) Create/Update the Squid basic auth password file
#    - Use bcrypt (-B) for stronger hashing when available
#    - Use -c only if file doesn't exist; otherwise update user entry without wiping others
log "Creating/updating Squid password file at: ${SQUID_PASSWD_FILE}"

# Ensure directory exists
install -d -m 0750 -o root -g squid /etc/squid || true

if [[ ! -f "${SQUID_PASSWD_FILE}" ]]; then
  # Create new password file
  # Note: htpasswd reads the password from stdin if you use it that way; we avoid interactive prompts.
  printf "%s\n" "${AUTH_PASS}" | htpasswd -Bci "${SQUID_PASSWD_FILE}" "${AUTH_USER}"
else
  # Update/add user in existing file (do NOT use -c to avoid overwriting)
  printf "%s\n" "${AUTH_PASS}" | htpasswd -Bi "${SQUID_PASSWD_FILE}" "${AUTH_USER}"
fi

# Tighten permissions so only root + squid group can read it
chown root:squid "${SQUID_PASSWD_FILE}"
chmod 0640 "${SQUID_PASSWD_FILE}"

# 3) Back up the existing Squid configuration
if [[ -f "${SQUID_CONF}" ]]; then
  TS="$(date +%Y%m%d-%H%M%S)"
  BACKUP="${SQUID_CONF}.bak.${TS}"
  log "Backing up existing Squid config: ${SQUID_CONF} -> ${BACKUP}"
  cp -a "${SQUID_CONF}" "${BACKUP}"
else
  warn "Squid config not found at ${SQUID_CONF}. Creating a new one."
fi

# 4) Write a clean, minimal Squid config that enforces authentication
#
#    Key lines explained:
#     - auth_param basic program ... : tells Squid how to validate usernames/passwords
#     - acl authenticated proxy_auth REQUIRED : defines an ACL that matches authenticated users
#     - http_access allow authenticated : allow only authenticated users
#     - http_access deny all : deny everyone else
#
#    Also includes safe defaults:
#     - localnet ACLs can be adjusted, but we *still* require auth for access
#     - basic listening port
#
log "Writing Squid configuration to ${SQUID_CONF} (authentication required)..."

cat > "${SQUID_CONF}" <<EOF
# -----------------------------------------------------------------------------
# Squid Configuration (AlmaLinux 10)
# Generated by installer script on: $(date -Is)
#
# This config requires BASIC authentication for all proxy access.
# User credentials are stored in: ${SQUID_PASSWD_FILE}
# Proxy listens on: ${SQUID_PORT}
# -----------------------------------------------------------------------------

# Listen on the default proxy port (can be changed)
http_port ${SQUID_PORT}

# -------------------------------------------------------------------
# Basic Authentication
# -------------------------------------------------------------------
# Use NCSA-style password file authentication.
# 'basic_ncsa_auth' is provided by the Squid package.
auth_param basic program /usr/lib64/squid/basic_ncsa_auth ${SQUID_PASSWD_FILE}

# Authentication realm presented to clients (browser/app prompt)
auth_param basic realm Squid Proxy Authentication

# Cache credentials in memory for a bit (reduces repeated prompts)
auth_param basic credentialsttl 2 hours

# Define an ACL that matches authenticated users
acl authenticated proxy_auth REQUIRED

# -------------------------------------------------------------------
# (Optional) Define which source networks are allowed to even reach the proxy
# You can tighten this to your LAN CIDR(s). Examples:
#   acl mylan src 192.168.0.0/16
#   acl mylan src 10.0.0.0/8
# For now, we keep it open at the network layer and enforce authentication.
# -------------------------------------------------------------------

# -------------------------------------------------------------------
# Access Rules (Order matters!)
# -------------------------------------------------------------------
# Allow access ONLY if the user authenticates
http_access allow authenticated

# Deny everything else
http_access deny all

# -------------------------------------------------------------------
# Logging
# -------------------------------------------------------------------
access_log /var/log/squid/access.log squid

# -------------------------------------------------------------------
# Basic runtime settings (safe defaults)
# -------------------------------------------------------------------
cache_mem 256 MB
maximum_object_size_in_memory 512 KB

# Use the distro default cache_dir location/size
cache_dir ufs /var/spool/squid 1000 16 256

# Recommended: let Squid determine visible hostname automatically
# (or set a specific name if you want)
# visible_hostname squid-proxy

# -----------------------------------------------------------------------------
EOF

# 5) Ensure Squid cache directories exist and permissions are correct
#    'squid -z' initializes the cache dirs based on cache_dir lines.
log "Initializing Squid cache directories..."
squid -z

# 6) SELinux notes (non-destructive)
#    On SELinux-enforcing systems, Squid usually works out of the box for 80/443.
#    If you proxy to unusual ports and see denials, you may need:
#      setsebool -P squid_connect_any 1
#
#    We do NOT enable it automatically unless you uncomment the line below.
if cmd_exists getenforce; then
  SELINUX_STATUS="$(getenforce || true)"
  log "SELinux status: ${SELINUX_STATUS}"
  if [[ "${SELINUX_STATUS}" == "Enforcing" ]]; then
    warn "SELinux is Enforcing. If you later see denied connections to non-standard ports,"
    warn "consider: setsebool -P squid_connect_any 1"
    # Uncomment the next line ONLY if you intentionally want Squid to connect anywhere:
    # setsebool -P squid_connect_any 1
  fi
fi

# 7) Validate configuration before starting
log "Validating Squid configuration..."
squid -k parse

# 8) Enable and start the Squid service
log "Enabling and starting Squid..."
systemctl enable --now squid

# 9) Open firewall port if firewalld is running
if systemctl is-active --quiet firewalld; then
  log "firewalld is active: opening TCP port ${SQUID_PORT}..."
  firewall-cmd --permanent --add-port="${SQUID_PORT}/tcp"
  firewall-cmd --reload
else
  warn "firewalld is not active. Skipping firewall configuration."
fi

# 10) Show status + quick usage tip
log "Squid is installed and configured."
log "Service status:"
systemctl --no-pager --full status squid || true

cat <<'EOT'

------------------------------------------------------------------------------
Client usage (examples):

1) Browser:
   - Set HTTP/HTTPS proxy to: <SERVER_IP>:3128
   - When prompted:
       Username: cent
       Password: sgsec@1390

2) curl (HTTP):
   curl -x http://cent:sgsec@1390@<SERVER_IP>:3128 http://example.com

Logs:
  - /var/log/squid/access.log

Config:
  - /etc/squid/squid.conf
------------------------------------------------------------------------------

EOT