CREATE TABLE agenda_items
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    meeting_id       BIGINT                                  NOT NULL,
    topic            VARCHAR(255)                            NOT NULL,
    description      TEXT,
    display_order    INTEGER                                 NOT NULL,
    duration_minutes INTEGER,
    presenter_id     BIGINT,
    CONSTRAINT pk_agenda_items PRIMARY KEY (id)
);

CREATE TABLE app_user_roles
(
    app_user_id BIGINT NOT NULL,
    role_id     BIGINT NOT NULL,
    CONSTRAINT pk_app_user_roles PRIMARY KEY (app_user_id, role_id)
);

CREATE TABLE app_users
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_type           VARCHAR(31)                             NOT NULL,
    first_name          VARCHAR(255),
    last_name           VARCHAR(255),
    username            VARCHAR(50),
    password            VARCHAR(255),
    email               VARCHAR(255),
    avatar_url          VARCHAR(512),
    created_at          TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at          TIMESTAMP(6) WITHOUT TIME ZONE,
    deleted             BOOLEAN,
    department          VARCHAR(255),
    availability_status VARCHAR(255),
    job_title           VARCHAR(255),
    manager_id          BIGINT,
    company_name        VARCHAR(255),
    phone               VARCHAR(255),
    CONSTRAINT pk_app_users PRIMARY KEY (id)
);

CREATE TABLE categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE meeting_notes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    meeting_id BIGINT                                  NOT NULL,
    author_id  BIGINT                                  NOT NULL,
    content    TEXT                                    NOT NULL,
    type       VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    CONSTRAINT pk_meeting_notes PRIMARY KEY (id)
);

CREATE TABLE meeting_participants
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    meeting_id  BIGINT                                  NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    rsvp_status VARCHAR(255)                            NOT NULL,
    attended    BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_meeting_participants PRIMARY KEY (id)
);

CREATE TABLE meetings
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(255)                            NOT NULL,
    description  TEXT,
    team_id      BIGINT                                  NOT NULL,
    organizer_id BIGINT                                  NOT NULL,
    start_time   TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    end_time     TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    location     VARCHAR(1000),
    status       VARCHAR(255)                            NOT NULL,
    active       BOOLEAN                                 NOT NULL,
    created_at   TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    updated_at   TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    CONSTRAINT pk_meetings PRIMARY KEY (id)
);

CREATE TABLE permissions
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code        VARCHAR(100)                            NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_permissions PRIMARY KEY (id)
);

CREATE TABLE role_permissions
(
    permission_id BIGINT NOT NULL,
    role_id       BIGINT NOT NULL,
    CONSTRAINT pk_role_permissions PRIMARY KEY (permission_id, role_id)
);

CREATE TABLE roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE sla_contracts
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    contract_name       VARCHAR(255),
    service_scope       VARCHAR(255),
    response_time_hours INTEGER,
    is_active           BOOLEAN,
    created_at          TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at          TIMESTAMP(6) WITHOUT TIME ZONE,
    customer_id         BIGINT,
    category_id         BIGINT,
    CONSTRAINT pk_sla_contracts PRIMARY KEY (id)
);

CREATE TABLE tasks
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title              VARCHAR(255)                            NOT NULL,
    description        TEXT,
    status             VARCHAR(255)                            NOT NULL,
    priority           VARCHAR(255)                            NOT NULL,
    progress           INTEGER                                 NOT NULL,
    due_date           TIMESTAMP(6) WITHOUT TIME ZONE,
    created_at         TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at         TIMESTAMP(6) WITHOUT TIME ZONE,
    completed_at       TIMESTAMP(6) WITHOUT TIME ZONE,
    active             BOOLEAN                                 NOT NULL,
    assigned_member_id BIGINT,
    meeting_id         BIGINT,
    created_by_id      BIGINT,
    CONSTRAINT pk_tasks PRIMARY KEY (id)
);

CREATE TABLE team_memberships
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    team_id   BIGINT                                  NOT NULL,
    user_id   BIGINT                                  NOT NULL,
    role      VARCHAR(255)                            NOT NULL,
    joined_at TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    CONSTRAINT pk_team_memberships PRIMARY KEY (id)
);

CREATE TABLE teams
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description TEXT,
    active      BOOLEAN                                 NOT NULL,
    created_at  TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    CONSTRAINT pk_teams PRIMARY KEY (id)
);

CREATE TABLE ticket_attachments
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ticket_id      BIGINT,
    message_id     BIGINT,
    file_name      VARCHAR(255),
    content_type   VARCHAR(100),
    storage_key    VARCHAR(255),
    size           BIGINT,
    uploaded_at    TIMESTAMP(6) WITHOUT TIME ZONE,
    uploaded_by_id BIGINT,
    CONSTRAINT pk_ticket_attachments PRIMARY KEY (id)
);

CREATE TABLE ticket_messages
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ticket_id        BIGINT,
    sender_id        BIGINT,
    message          TEXT,
    sent_at          TIMESTAMP(6) WITHOUT TIME ZONE,
    read_by_customer BOOLEAN,
    read_by_team     BOOLEAN,
    CONSTRAINT pk_ticket_messages PRIMARY KEY (id)
);

CREATE TABLE ticket_status_histories
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ticket_id     BIGINT,
    old_status    VARCHAR(50),
    new_status    VARCHAR(50),
    changed_at    TIMESTAMP(6) WITHOUT TIME ZONE,
    changed_by_id BIGINT,
    note          TEXT,
    CONSTRAINT pk_ticket_status_histories PRIMARY KEY (id)
);

CREATE TABLE tickets
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title              VARCHAR(255),
    description        TEXT,
    status             VARCHAR(255),
    priority           VARCHAR(255),
    emergency          BOOLEAN                                 NOT NULL,
    due_date           TIMESTAMP(6) WITHOUT TIME ZONE,
    created_at         TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at         TIMESTAMP(6) WITHOUT TIME ZONE,
    customer_id        BIGINT,
    sla_contract_id    BIGINT,
    assigned_member_id BIGINT,
    CONSTRAINT pk_tickets PRIMARY KEY (id)
);

CREATE TABLE user_permission_grants
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id       BIGINT                                  NOT NULL,
    permission_id BIGINT                                  NOT NULL,
    effect        VARCHAR(255),
    CONSTRAINT pk_user_permission_grants PRIMARY KEY (id)
);

CREATE TABLE user_resource_scopes
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id       BIGINT                                  NOT NULL,
    resource_type VARCHAR(255),
    scope         VARCHAR(255),
    CONSTRAINT pk_user_resource_scopes PRIMARY KEY (id)
);

ALTER TABLE team_memberships
    ADD CONSTRAINT uc_a0cf3c8279784a5033000d092 UNIQUE (team_id, user_id);

ALTER TABLE app_users
    ADD CONSTRAINT uc_app_users_username UNIQUE (username);

ALTER TABLE categories
    ADD CONSTRAINT uc_categories_name UNIQUE (name);

ALTER TABLE meeting_participants
    ADD CONSTRAINT uc_d1a7a5b033c7e502845f706a8 UNIQUE (meeting_id, user_id);

ALTER TABLE permissions
    ADD CONSTRAINT uc_permissions_code UNIQUE (code);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_name UNIQUE (name);

ALTER TABLE agenda_items
    ADD CONSTRAINT FK_AGENDA_ITEMS_ON_MEETING FOREIGN KEY (meeting_id) REFERENCES meetings (id);

ALTER TABLE agenda_items
    ADD CONSTRAINT FK_AGENDA_ITEMS_ON_PRESENTER FOREIGN KEY (presenter_id) REFERENCES app_users (id);

ALTER TABLE app_users
    ADD CONSTRAINT FK_APP_USERS_ON_MANAGER FOREIGN KEY (manager_id) REFERENCES app_users (id);

ALTER TABLE meetings
    ADD CONSTRAINT FK_MEETINGS_ON_ORGANIZER FOREIGN KEY (organizer_id) REFERENCES app_users (id);

ALTER TABLE meetings
    ADD CONSTRAINT FK_MEETINGS_ON_TEAM FOREIGN KEY (team_id) REFERENCES teams (id);

ALTER TABLE meeting_notes
    ADD CONSTRAINT FK_MEETING_NOTES_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES app_users (id);

ALTER TABLE meeting_notes
    ADD CONSTRAINT FK_MEETING_NOTES_ON_MEETING FOREIGN KEY (meeting_id) REFERENCES meetings (id);

ALTER TABLE meeting_participants
    ADD CONSTRAINT FK_MEETING_PARTICIPANTS_ON_MEETING FOREIGN KEY (meeting_id) REFERENCES meetings (id);

ALTER TABLE meeting_participants
    ADD CONSTRAINT FK_MEETING_PARTICIPANTS_ON_USER FOREIGN KEY (user_id) REFERENCES app_users (id);

ALTER TABLE sla_contracts
    ADD CONSTRAINT FK_SLA_CONTRACTS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE sla_contracts
    ADD CONSTRAINT FK_SLA_CONTRACTS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES app_users (id);

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_ON_ASSIGNED_MEMBER FOREIGN KEY (assigned_member_id) REFERENCES app_users (id);

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_ON_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES app_users (id);

ALTER TABLE tasks
    ADD CONSTRAINT FK_TASKS_ON_MEETING FOREIGN KEY (meeting_id) REFERENCES meetings (id);

ALTER TABLE team_memberships
    ADD CONSTRAINT FK_TEAM_MEMBERSHIPS_ON_TEAM FOREIGN KEY (team_id) REFERENCES teams (id);

ALTER TABLE team_memberships
    ADD CONSTRAINT FK_TEAM_MEMBERSHIPS_ON_USER FOREIGN KEY (user_id) REFERENCES app_users (id);

ALTER TABLE tickets
    ADD CONSTRAINT FK_TICKETS_ON_ASSIGNED_MEMBER FOREIGN KEY (assigned_member_id) REFERENCES app_users (id);

ALTER TABLE tickets
    ADD CONSTRAINT FK_TICKETS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES app_users (id);

ALTER TABLE tickets
    ADD CONSTRAINT FK_TICKETS_ON_SLA_CONTRACT FOREIGN KEY (sla_contract_id) REFERENCES sla_contracts (id);

ALTER TABLE ticket_attachments
    ADD CONSTRAINT FK_TICKET_ATTACHMENTS_ON_MESSAGE FOREIGN KEY (message_id) REFERENCES ticket_messages (id);

ALTER TABLE ticket_attachments
    ADD CONSTRAINT FK_TICKET_ATTACHMENTS_ON_TICKET FOREIGN KEY (ticket_id) REFERENCES tickets (id);

ALTER TABLE ticket_attachments
    ADD CONSTRAINT FK_TICKET_ATTACHMENTS_ON_UPLOADED_BY FOREIGN KEY (uploaded_by_id) REFERENCES app_users (id);

ALTER TABLE ticket_messages
    ADD CONSTRAINT FK_TICKET_MESSAGES_ON_SENDER FOREIGN KEY (sender_id) REFERENCES app_users (id);

ALTER TABLE ticket_messages
    ADD CONSTRAINT FK_TICKET_MESSAGES_ON_TICKET FOREIGN KEY (ticket_id) REFERENCES tickets (id);

ALTER TABLE ticket_status_histories
    ADD CONSTRAINT FK_TICKET_STATUS_HISTORIES_ON_CHANGED_BY FOREIGN KEY (changed_by_id) REFERENCES app_users (id);

ALTER TABLE ticket_status_histories
    ADD CONSTRAINT FK_TICKET_STATUS_HISTORIES_ON_TICKET FOREIGN KEY (ticket_id) REFERENCES tickets (id);

ALTER TABLE user_permission_grants
    ADD CONSTRAINT FK_USER_PERMISSION_GRANTS_ON_PERMISSION FOREIGN KEY (permission_id) REFERENCES permissions (id);

ALTER TABLE user_permission_grants
    ADD CONSTRAINT FK_USER_PERMISSION_GRANTS_ON_USER FOREIGN KEY (user_id) REFERENCES app_users (id);

ALTER TABLE user_resource_scopes
    ADD CONSTRAINT FK_USER_RESOURCE_SCOPES_ON_USER FOREIGN KEY (user_id) REFERENCES app_users (id);

ALTER TABLE app_user_roles
    ADD CONSTRAINT fk_appuserol_on_app_user FOREIGN KEY (app_user_id) REFERENCES app_users (id);

ALTER TABLE app_user_roles
    ADD CONSTRAINT fk_appuserol_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE role_permissions
    ADD CONSTRAINT fk_rolper_on_permission FOREIGN KEY (permission_id) REFERENCES permissions (id);

ALTER TABLE role_permissions
    ADD CONSTRAINT fk_rolper_on_role FOREIGN KEY (role_id) REFERENCES roles (id);