CREATE TABLE teams
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX uq_teams_active_name
    ON teams (LOWER(name))
    WHERE active = TRUE;

CREATE TABLE team_memberships
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(50) NOT NULL,
    joined_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uq_team_membership UNIQUE (team_id, user_id),
    CONSTRAINT fk_team_membership_team FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE CASCADE,
    CONSTRAINT fk_team_membership_user FOREIGN KEY (user_id) REFERENCES app_users (id) ON DELETE CASCADE
);

CREATE TABLE meetings
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    team_id BIGINT NOT NULL,
    organizer_id BIGINT NOT NULL,
    start_time TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    end_time TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    location VARCHAR(1000),
    status VARCHAR(50) NOT NULL DEFAULT 'SCHEDULED',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT chk_meeting_time_range CHECK (end_time > start_time),
    CONSTRAINT fk_meeting_team FOREIGN KEY (team_id) REFERENCES teams (id),
    CONSTRAINT fk_meeting_organizer FOREIGN KEY (organizer_id) REFERENCES app_users (id)
);

CREATE TABLE agenda_items
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id BIGINT NOT NULL,
    topic VARCHAR(255) NOT NULL,
    description TEXT,
    display_order INTEGER NOT NULL,
    duration_minutes INTEGER,
    presenter_id BIGINT,
    CONSTRAINT chk_agenda_display_order CHECK (display_order >= 0),
    CONSTRAINT chk_agenda_duration CHECK (duration_minutes IS NULL OR duration_minutes > 0),
    CONSTRAINT fk_agenda_meeting FOREIGN KEY (meeting_id) REFERENCES meetings (id) ON DELETE CASCADE,
    CONSTRAINT fk_agenda_presenter FOREIGN KEY (presenter_id) REFERENCES app_users (id) ON DELETE SET NULL
);

CREATE TABLE meeting_participants
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    rsvp_status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    attended BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_meeting_participant UNIQUE (meeting_id, user_id),
    CONSTRAINT fk_participant_meeting FOREIGN KEY (meeting_id) REFERENCES meetings (id) ON DELETE CASCADE,
    CONSTRAINT fk_participant_user FOREIGN KEY (user_id) REFERENCES app_users (id) ON DELETE CASCADE
);

CREATE TABLE meeting_notes
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    type VARCHAR(50) NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_meeting_note_meeting FOREIGN KEY (meeting_id) REFERENCES meetings (id) ON DELETE CASCADE,
    CONSTRAINT fk_meeting_note_author FOREIGN KEY (author_id) REFERENCES app_users (id)
);

CREATE INDEX idx_team_memberships_team_id ON team_memberships (team_id);
CREATE INDEX idx_team_memberships_user_id ON team_memberships (user_id);
CREATE INDEX idx_meetings_team_start_time ON meetings (team_id, start_time);
CREATE INDEX idx_meetings_organizer_id ON meetings (organizer_id);
CREATE INDEX idx_meeting_participants_user_id ON meeting_participants (user_id);
CREATE INDEX idx_agenda_items_meeting_order ON agenda_items (meeting_id, display_order);
CREATE INDEX idx_meeting_notes_meeting_created ON meeting_notes (meeting_id, created_at);

ALTER TABLE tasks ADD COLUMN IF NOT EXISTS meeting_id BIGINT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS created_by_id BIGINT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP(6) WITHOUT TIME ZONE;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE tasks
    ADD CONSTRAINT fk_tasks_meeting FOREIGN KEY (meeting_id) REFERENCES meetings (id) ON DELETE SET NULL;
ALTER TABLE tasks
    ADD CONSTRAINT fk_tasks_created_by FOREIGN KEY (created_by_id) REFERENCES app_users (id) ON DELETE SET NULL;

CREATE INDEX idx_tasks_meeting_id ON tasks (meeting_id);
CREATE INDEX idx_tasks_active ON tasks (active);
